name: "SQUAADS Auto-Reports"
description: "Automatically transform PR technical changes into business-centric ROI reports."
author: "SQUAADS"
branding:
  icon: "activity"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ github.token }}
  gemini-api-key:
    description: "Google Gemini API Key"
    required: true
  aura-config:
    description: "JSON string for branding and behavior configuration"
    required: false

runs:
  using: "node24"
  main: "dist/main.js"
