# .github/workflows/auto-reports.yml
name: Auto-Reports Business Value

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  generate-business-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SQUAADS Auto-Reports
        uses: YuniorGlez/auto-reports@main
        with:
          # Token de GitHub (automático)
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Pasar la API KEY directamente como input (MÁS RECOMENDADO EN 2026)
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          
          # Configuración personalizada
          aura-config: >-
            {
              "branding": {
                "projectName": "Mi Proyecto",
                "primaryColor": "#2563eb"
              },
              "behavior": {
                "language": "es"
              }
            }
